// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerClient interface {
	PaymentRequest(ctx context.Context, in *PaymentRequestMessage, opts ...grpc.CallOption) (*Result, error)
	CommunicationInfoRequest(ctx context.Context, in *Address, opts ...grpc.CallOption) (*CommunicationInfo, error)
	CrossPaymentPrepareRequest(ctx context.Context, in *CrossPaymentPrepareReqMessage, opts ...grpc.CallOption) (*Result, error)
	CrossPaymentCommitRequest(ctx context.Context, in *CrossPaymentCommitReqMessage, opts ...grpc.CallOption) (*Result, error)
}

type serverClient struct {
	cc grpc.ClientConnInterface
}

func NewServerClient(cc grpc.ClientConnInterface) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) PaymentRequest(ctx context.Context, in *PaymentRequestMessage, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/Server/paymentRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) CommunicationInfoRequest(ctx context.Context, in *Address, opts ...grpc.CallOption) (*CommunicationInfo, error) {
	out := new(CommunicationInfo)
	err := c.cc.Invoke(ctx, "/Server/communicationInfoRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) CrossPaymentPrepareRequest(ctx context.Context, in *CrossPaymentPrepareReqMessage, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/Server/crossPaymentPrepareRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) CrossPaymentCommitRequest(ctx context.Context, in *CrossPaymentCommitReqMessage, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/Server/crossPaymentCommitRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServer is the server API for Server service.
// All implementations must embed UnimplementedServerServer
// for forward compatibility
type ServerServer interface {
	PaymentRequest(context.Context, *PaymentRequestMessage) (*Result, error)
	CommunicationInfoRequest(context.Context, *Address) (*CommunicationInfo, error)
	CrossPaymentPrepareRequest(context.Context, *CrossPaymentPrepareReqMessage) (*Result, error)
	CrossPaymentCommitRequest(context.Context, *CrossPaymentCommitReqMessage) (*Result, error)
	mustEmbedUnimplementedServerServer()
}

// UnimplementedServerServer must be embedded to have forward compatible implementations.
type UnimplementedServerServer struct {
}

func (UnimplementedServerServer) PaymentRequest(context.Context, *PaymentRequestMessage) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaymentRequest not implemented")
}
func (UnimplementedServerServer) CommunicationInfoRequest(context.Context, *Address) (*CommunicationInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommunicationInfoRequest not implemented")
}
func (UnimplementedServerServer) CrossPaymentPrepareRequest(context.Context, *CrossPaymentPrepareReqMessage) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrossPaymentPrepareRequest not implemented")
}
func (UnimplementedServerServer) CrossPaymentCommitRequest(context.Context, *CrossPaymentCommitReqMessage) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrossPaymentCommitRequest not implemented")
}
func (UnimplementedServerServer) mustEmbedUnimplementedServerServer() {}

// UnsafeServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerServer will
// result in compilation errors.
type UnsafeServerServer interface {
	mustEmbedUnimplementedServerServer()
}

func RegisterServerServer(s grpc.ServiceRegistrar, srv ServerServer) {
	s.RegisterService(&Server_ServiceDesc, srv)
}

func _Server_PaymentRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).PaymentRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Server/paymentRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).PaymentRequest(ctx, req.(*PaymentRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_CommunicationInfoRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).CommunicationInfoRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Server/communicationInfoRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).CommunicationInfoRequest(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_CrossPaymentPrepareRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrossPaymentPrepareReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).CrossPaymentPrepareRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Server/crossPaymentPrepareRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).CrossPaymentPrepareRequest(ctx, req.(*CrossPaymentPrepareReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_CrossPaymentCommitRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrossPaymentCommitReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).CrossPaymentCommitRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Server/crossPaymentCommitRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).CrossPaymentCommitRequest(ctx, req.(*CrossPaymentCommitReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Server_ServiceDesc is the grpc.ServiceDesc for Server service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Server_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "paymentRequest",
			Handler:    _Server_PaymentRequest_Handler,
		},
		{
			MethodName: "communicationInfoRequest",
			Handler:    _Server_CommunicationInfoRequest_Handler,
		},
		{
			MethodName: "crossPaymentPrepareRequest",
			Handler:    _Server_CrossPaymentPrepareRequest_Handler,
		},
		{
			MethodName: "crossPaymentCommitRequest",
			Handler:    _Server_CrossPaymentCommitRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
